### ISSUE TITLE
TypeError: Cannot read property 'messages' of undefined

### ISSUE THREAD

**Issue by hylle** [AtomLinter/linter-phpcs#45] opened 2015-07-15 14:08 UTC
```
TypeError: Cannot read property 'messages' of undefined
  at /Users/jh/.atom/packages/linter-phpcs/lib/main.coffee:75:40
  at process._tickCallback (node.js:367:9)
```

This happens when saving a .phtml file, while i have "*.phtml" in the ignore setting.

**Comment by steelbrain** [comment] 2015-07-15 14:22
Dupe of https://github.com/AtomLinter/linter-phpcs/issues/43

**Closed by steelbrain** 2015-07-15 14:22 UTC
