### ISSUE TITLE
Issues with Blade templates

### ISSUE THREAD

**Issue by curtisblackwell** [AtomLinter/linter-phpcs#43] opened 2015-07-15 02:26 UTC
I'm getting this error in Blade templates.

```
Cannot read property 'messages' of undefined
TypeError: Cannot read property 'messages' of undefined
  at /Users/curtisblackwell/.atom/packages/linter-phpcs/lib/main.coffee:75:40
  at process._tickCallback (node.js:367:9)
```

I checked my Ignore settings, and I had `*.blade.php` in there. I tried removing it, saw that Blade and Twig are both ignored by default. Still get the error even at default.

**Comment by steelbrain** [comment] 2015-07-15 14:22
Dupe of https://github.com/AtomLinter/linter-phpcs/issues/38

**Closed by steelbrain** 2015-07-15 14:22 UTC
Labels: bug
