### ISSUE TITLE
Error running PHPCS Error: Invalid point encountered!

### ISSUE THREAD

**Issue by wpdevco** [AtomLinter/linter-phpcs#267] opened 2017-05-25 19:06 UTC
Atom v1.17.1
PHP v7.1.5
linter-phpcs v1.6.4
PHP_CodeSniffer v2.9.1
Using [WordPress sniffs](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards)

Tab length set to 4 and `phpcs --config-set encoding utf-8`.

***

As an example, this file...

```php
<?php

add_action( 'genesis_before_header', 'gmb_add_primary_navigation' );
function gmb_add_primary_navigation() {

	$nav = wp_nav_menu( array(
		'theme_location' => 'primary',
		'container'      => false,
		'menu_class'     => 'nav-primary__list list_minimal list_row hide-below-md',
		'echo'           => 0
	) );

	echo $nav;
}
```
...produces this error:

![image 2017-05-25 at 12 43 46 pm](https://cloud.githubusercontent.com/assets/879872/26467527/d4107c14-4147-11e7-9b8e-da159f91be69.png)

**Comment by Arcanemagus** [comment] 2017-05-25 19:24
Are you able to share a file that reproduces this? Without that it's impossible to tell if this is a problem in our attempts to work around PHPCS's terrible tab handling, or yet another bug in PHPCS itself.

**Comment by wpdevco** [comment] 2017-05-25 19:40
Sure:

```php
<?php

add_action( 'genesis_before_header', 'gmb_add_primary_navigation' );
function gmb_add_primary_navigation() {

	$nav = wp_nav_menu( array(
		'theme_location' => 'primary',
		'container' => false,
		'menu_class' => 'nav-primary__list list_minimal list_row hide-below-md',
		'echo' => 0
	) );
}
```

**Comment by miklb** [comment] 2017-05-30 01:25
Getting same thing w/ 2.8.1 of `php-code-sniffer`. I tried switching to 3.0.0 (available via Homebrew) and it completely breaks.

**Comment by miklb** [comment] 2017-05-30 01:37
Update: I updated the WP Code Sniffer rules and my error went away. YMMV

**Comment by rclations** [comment] 2017-06-06 20:32
same thing herer

**Comment by mundschenk-at** [comment] 2017-06-07 10:08
@miklb 3.0.0. does not yet work with many existing sniff sets, including WPCS and PHPCompatibility.

**Comment by rclations** [comment] 2017-06-07 15:45
@mundschenk-at what's needed to make it compatible with WPCS? Happy to contribute, just not sure where to start and what's needed

**Comment by miklb** [comment] 2017-06-07 15:56
@mundschenk-at understood, was just pointing out that I had also tried updating to latest and still didn't work.

**Comment by mundschenk-at** [comment] 2017-06-07 16:07
@rclations A bit off-topic here, but [quite a lot](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/718). (To clarify: @miklb & I were talking about the underlying `phpcs` version 3.0.0, not `linter-phpcs`.)

**Comment by rclations** [comment] 2017-06-07 16:09
@mundschenk-at many thanks for the pointer in the right direction.

**Comment by CyanSalt** [comment] 2017-06-08 06:35
I met the same error today and I tried fixing it.
After reading the code I noticed the function `fixPHPCSColumn` in `main.js`, so I add some config to settings about the "Tab Width":
```cson
"linter-phpcs":
  tabWidth: 4
```
Now it works well.

**Comment by miklb** [comment] 2017-06-08 08:17
@CyanSalt that fixed it for me 👍

**Comment by wpdevco** [comment] 2017-06-08 16:45
Nada for me. Same issue.

**Comment by wpdevco** [comment] 2017-06-08 16:48
Fixed for me, too. 👍

**Comment by Arcanemagus** [comment] 2017-06-09 17:05
Certain combinations of PHPCS versions and certain standards can make setting that value manually required, all due to how PHPCS allows sniffs to consider tabs to be more than one character for some bizarre reason. There is currently a [list of overrides] for known broken standards, if you know of more that try to force that value in the standard (thus breaking everything) feel free to submit a PR updating that list.

Marking this as closed since this is yet another case where PHPCS's broken tab handling has caused it to report a point that doesn't exist.

**Closed by Arcanemagus** 2017-06-09 17:05 UTC

**Comment by Arcanemagus** [comment] 2017-06-14 21:41
Note that PHPCS v3.0.1 (just released) fixes this bug introduced in v2. 🎉
