### ISSUE TITLE
Ignore option doesn't work.

### ISSUE THREAD

**Issue by Xety** [AtomLinter/linter-phpcs#66] opened 2015-10-06 11:42 UTC
Hello,

I have the following settings :
![wpbhk50](https://cloud.githubusercontent.com/assets/8210023/10307508/dd9c8820-6c2f-11e5-88ca-3c1e47923efa.png)

But it doesn't work :
![screenshot_20](https://cloud.githubusercontent.com/assets/8210023/10307542/04fd607e-6c30-11e5-8777-50bf6a17c683.png)

**Comment by steelbrain** [comment] 2015-10-06 13:14
Can we get a non-trimmed version of the first picture please?

**Comment by Xety** [comment] 2015-10-06 14:04
Yes of course :
![67tdtoh](https://cloud.githubusercontent.com/assets/8210023/10310762/d5c71304-6c43-11e5-8300-9788f6cb177c.png)

**Comment by Arcanemagus** [comment] 2015-10-06 16:56
I'm actually not sure why that option is even in there. The [documentation](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-files-and-folders) basically says it is meant for when you are running `phpcs` on an entire directory, but we are no matter what running on a single file.

I think what is going on here is that it sees the ignore option... but then ignores it since we explicitly told it to lint that file. In this case I would either put the code described in the link above at the top of the file, or change the type of the file to not be PHP (but then you lose syntax highlighting, so that is most definitely not ideal).

I'm going to close this issue and submit a PR soon to remove that option as I have no idea how it would ever be relevant in this usage.

**Comment by Xety** [comment] 2015-10-06 18:02
This option worked fine 1/2 weeks ago. I remember it was me who added this option in https://github.com/AtomLinter/linter-phpcs/commit/a936699245e020b5da59491232cf26b1641f68d9. Something has broke it.

**Comment by Arcanemagus** [comment] 2015-10-06 18:34
@Xety possibly broken on `phpcs`'s side then? Nothing should have changed with the running of it here.

(I still don't see how that setting is relevant for a single file...)

**Comment by Arcanemagus** [comment] 2015-10-06 18:46
Okay, did some testing here, it works on the command line with v2.3.4, but not within Atom under `linter-phpcs`. I'll see if I can figure it out.

**Comment by Xety** [comment] 2015-10-06 18:56
I just tested previous version and 1.0.7 => work, 1.1.0 => broke.

**Comment by Arcanemagus** [comment] 2015-10-06 18:59
It's a bug in `phpcs`, we moved to feeding it the file content via `stdin` to enable linting on the fly. The issue is that, even though we modify the text to tell it the file name, it still considers the file name to be "STDIN" for the purposes of the ignore test.

So the options are either:
* Disable this option
* Re-implement it locally to stop execution if a matching pattern is found
* Disable linting on the fly

As I personally use lintOnFly I'm not going to disable that, which leaves us the first two options. Does anyone want to submit a PR for the second?

**Comment by skyrpex** [comment] 2015-10-06 20:30
I could implement option two using [isaacs/minimatch](https://github.com/isaacs/minimatch), for example. Should I?

**Comment by Arcanemagus** [comment] 2015-10-06 20:51
Go for it :smile:, as long as it works properly I'd be happy to merge it.

**Comment by tchaffee** [comment] 2015-10-08 14:00
I had to turn off linter-phpcs because of this bug. Eagerly awaiting a fix.

**Closed** 2015-10-13 04:27 UTC

**Comment by Arcanemagus** [comment] 2015-10-13 05:05
Fixed version published in v1.2.1, enjoy and please report any further issues you find!

**Comment by Xety** [comment] 2015-10-13 09:56
It work well now, thanks !

**Comment by skyrpex** [comment] 2015-10-13 09:58
:+1:
