### ISSUE TITLE
Package.getActivationCommands is deprecated.

### ISSUE THREAD

**Issue by fredcamps** [AtomLinter/linter-phpcs#18] opened 2015-05-13 21:15 UTC
Use `activationCommands` instead of `activationEvents` in your package.json
Commands should be grouped by selector as follows:
```json
  "activationCommands": {
    "atom-workspace": ["foo:bar", "foo:baz"],
    "atom-text-editor": ["foo:quux"]
  }
```
```
Package.getActivationCommands (/usr/share/atom/resources/app.asar/src/package.js:810:9)
Package.hasActivationCommands (/usr/share/atom/resources/app.asar/src/package.js:735:20)
<unknown> (/usr/share/atom/resources/app.asar/src/package.js:189:24)
Package.measure (/usr/share/atom/resources/app.asar/src/package.js:167:15)
```

**Comment by kevinsawicki** [comment] 2015-05-21 18:38
Fixed by https://github.com/AtomLinter/linter-phpcs/pull/22

**Closed by kevinsawicki** 2015-05-21 18:38 UTC

**Comment by Arcanemagus** [comment] 2016-10-10 20:56
Duplicate of #17.
