### ISSUE TITLE
Error: Process exited with non-zero code: 255

### ISSUE THREAD

**Issue by salt-lick** [AtomLinter/linter-phpcs#206] opened 2016-10-11 18:27 UTC
Upgraded to 1.5.0 and now I am getting 

```
Error: Process exited with non-zero code: 255
    at ChildProcess.<anonymous> (/Users/dev02/.atom/packages/linter-phpcs/node_modules/sb-exec/lib/index.js:60:22)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

**Comment by Arcanemagus** [comment] 2016-10-12 05:26
That's... rather impossible 😕. We are ignoring the exit code [here](https://github.com/AtomLinter/linter-phpcs/blob/v1.5.0/lib/main.js#L263).

Can you try re-installing the package?

**Comment by oknixus** [comment] 2016-10-12 06:17
@Arcanemagus After reinstalling the package, the error isn't be solved.

**Comment by oknixus** [comment] 2016-10-12 06:18
Atom 1.11.1
linter-phpcs 1.5.1

**Comment by oknixus** [comment] 2016-10-12 07:15
I reinstalled atom@1.10.2, the error isn't be solved.

**Comment by Arcanemagus** [comment] 2016-10-12 07:20
@steelbrain Any ideas here? I'm not sure how this could be breaking...

**Comment by salt-lick** [comment] 2016-10-12 10:50
Can confirm. Reinstalled, went to 1.4.1, installed 1.5 and still got this error.

If it helps - OSX 10.12 user

**Comment by steelbrain** [comment] 2016-10-12 14:26
@Arcanemagus There's no apparent way how it could be respecting exit code when we have told it to ignore. It would be very helpful if there was a way to repro this behavior locally

**Comment by Arcanemagus** [comment] 2016-10-12 16:41
@oknixus and @salt-lick are you seeing this on all files, or only certain ones? If it's certain files are you able to share them?

**Comment by oknixus** [comment] 2016-10-14 01:40
![image](https://cloud.githubusercontent.com/assets/4592706/19372825/e8563944-91f1-11e6-8c6b-e761c846311a.png)

linter-phpcs 1.5.2
![image](https://cloud.githubusercontent.com/assets/4592706/19372853/0dd387d0-91f2-11e6-9d83-b8510398016a.png)

Error: Process exited with non-zero code: 255
![image](https://cloud.githubusercontent.com/assets/4592706/19372864/254f5c86-91f2-11e6-87e3-f428e50d4781.png)

Error: Process exited with non-zero code: 255
    at ChildProcess.<anonymous> (/Users/KJRS/.atom/packages/linter-phpcs/node_modules/sb-exec/lib/index.js:60:22)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

**Comment by Arcanemagus** [comment] 2016-10-14 02:05
Hmmm, can you go to `/Users/KJRS/.atom/packages/linter-phpcs` and run `npm ls --depth=0`?

**Comment by danielmilner** [comment] 2016-10-14 16:33
I am also experiencing this issue under practically the same circumstances. Below is the output from running `nom ls --depth=0`

├── atom-linter@8.0.0
├── atom-package-deps@4.3.1
├── atom-package-path@1.1.0
├── balanced-match@0.4.2
├── brace-expansion@1.1.6
├── concat-map@0.0.1
├── consistent-env@1.3.0
├── escape-html@1.0.3
├── lodash.uniq@4.5.0
├── minimatch@3.0.3
├── named-js-regexp@1.3.1
├── os-tmpdir@1.0.2
├── sb-callsite@1.1.2
├── sb-exec@3.1.0
├── sb-memoize@1.0.2
├── sb-npm-path@2.0.0
├── sb-promisify@2.0.1
└── tmp@0.0.29

**Comment by Arcanemagus** [comment] 2016-10-14 18:23
@danielmilner What OS are you on? Version of Atom? Is Atom actually loading `sb-exec` from `linter-phpcs`, or a different package that might have an older version?

The last one is the trickiest, as it can change on each launch of Atom, and can only be determined by annoying tracing in the Developer Console, or from the stack trace. That being said... any version past 2.0.2 of `sb-exec` _should_ be working perfectly.

**Comment by danielmilner** [comment] 2016-10-14 18:43
@Arcanemagus 
OS: macOS Sierra 10.12
Atom: 1.11.1

To test the last one, I disabled all non-core packages except for `linter` and `linter-phpcs`, then restarted Atom. Error message still appears.

**Comment by Arcanemagus** [comment] 2016-10-14 18:51
@steelbrain Are you able to reproduce this locally? I have no way to test this myself and it seems to be related to macOS 10.12 as we aren't hitting it on the Travis-CI OS X builds.

**Comment by danielmilner** [comment] 2016-10-14 18:55
@Arcanemagus @steelbrain For what it's worth, this is happening on my MacBook, but I also have an iMac with the same configuration where it IS working properly.

**Comment by danielmilner** [comment] 2016-10-14 19:06
I reinstalled PHP CodeSniffer with Composer and pointed Atom to `/Users/danielmilner/.composer/vendor/bin/phpcs`

This appears to have solved my issue.

**Comment by Arcanemagus** [comment] 2016-10-14 19:24
Hmmm, how did you have it installed before?

**Comment by Arcanemagus** [comment] 2016-10-14 20:00
Okay, @steelbrain and I have worked out a theory as to what's happening here: `linter-phpcs` _is_ ignoring the exit code, but however you had `phpcs` installed before you switched to Composer was generating a badly written wrapper script, so instead of just forwarding on the exit code from PHPCS it was trying to call it, failing to find `phpcs` somehow, and putting the _text_ `Process exited with non-zero code: 255` out to `stderr`, which would then show in a similar manner to an unhandled _real_ exit code.

We can't confirm though until we get more information from you 😛.

**Comment by danielmilner** [comment] 2016-10-14 20:26
I wish that I could tell you how I had previously installed it, but I don't know what I had done differently initially. I'm 💯 sure it was a user error though :/

**Comment by jstahlmann** [comment] 2016-10-19 12:02
I had the same issue.
OS: macOS Sierra 10.12
Atom: 1.11.2

Reinstalling PHP_CodeSniffer with Composer and setting the phpcs-path in the atom package settings to _/Users/jstahl/.composer/vendor/bin/phpcs fixed the problem!

**Comment by salt-lick** [comment] 2016-10-19 13:21
I also did 

> composer global require "squizlabs/php_codesniffer=*"


and then edited my ~/.atom/config.cson file with the updated path to the phpcs bin file

> /Users/username/.composer/vendor/bin/phpcs


and this got me up and running. 

Thanks for the suggestions.

**Comment by Arcanemagus** [comment] 2016-10-24 18:49
Without any further information I'm going to close this as a user configuration issue. If anyone is running into this the solution seems to be "use composer to install it" 😉.

**Closed by Arcanemagus** 2016-10-24 18:49 UTC
Labels: question

**Comment by mikebronner** [comment] 2016-11-16 16:57
I'm having this issue as well. Reading the comments, could it be global vs project composer installation? Also, could running on PHP7 be an issue, where PHPCS is throwing an error, and the linter not handling it properly? (Just spitballing, because I have seen PHPCS behave oddly in conjunction with PHP7.

**Comment by Arcanemagus** [comment] 2016-11-17 00:57
@mikebronner Like has been said a few times in this issue, that message is quite deceptive: The _text_ `Error: Process exited with non-zero exit code: 255` is being output to `stderr`. The process that _linter-phpcs_ is calling has the exit code properly ignored, but expects output on `stdout` only, so when it sees the text on `stderr` it reports it.

I've been unable to get a system to get into a state where this happens, it seems to be a quirk for how some users (only on macOS!) are getting `phpcs` installed. If you want to help diagnose this issue check what `/Users/mike/.composer/vendor/bin/phpcs` actually is, my guess is that it's some form of wrapper script as that's the only thing we could think of that would cause this.

**Comment by aforward** [comment] 2016-12-29 14:12
I found this thread when debugging an issue and here is what I found.

If I ran phpcs from the command line, I would actually see the underlying error.

```
09:09 /tmp $ phpcs

Warning: include_once(PHP/CodeSniffer/CLI.php): failed to open stream: No such file or directory in /Users/aforward/pear/bin/phpcs on line 21

Warning: include_once(): Failed opening 'PHP/CodeSniffer/CLI.php' for inclusion (include_path='.:') in /Users/aforward/pear/bin/phpcs on line 21

Fatal error: Class 'PHP_CodeSniffer_CLI' not found in /Users/aforward/pear/bin/phpcs on line 24
```

I am not that familiar with the inner working of PEAR, so instead of getting to the root of the problem, I just patched it using the following

```
cd ~/pear/bin && ln -s ../share/pear/PHP PHP
```

Thanks to the help from http://stackoverflow.com/questions/14257209/php-codesniffer-include-once-error

When I go into ATOM, the error reported above by others is gone.

**Comment by Arcanemagus** [comment] 2017-01-06 21:05
Thanks for posting a workaround for those that installed using PEAR @aforward!

**Comment by mikebronner** [comment] 2017-01-06 23:26
I have not been getting the issue anymore since a few patches back ... not sure what fixed it, but thanks :) it seems to be working. Sorry for not getting back to you on the message above.
