### ISSUE TITLE
.js [sm]:362 linter-phpcs:: Invalid point encountered ....

### ISSUE THREAD

**Issue by nextgenthemes** [AtomLinter/linter-phpcs#304] opened 2017-12-06 21:13 UTC
System: Ubuntu 17.10
Atom Version: 1.22.1
PHP Version: 7.1
```
$ which phpcs
/home/user123/dev/wpcs/vendor/bin/phpcs
```

Installed WP Coding Standards that come with PHPCS in there a command like this

`composer create-project wp-coding-standards/wpcs --no-dev`

Config and files: https://github.com/nextgenthemes/advanced-responsive-video-embedder

```
.js [sm]:362 linter-phpcs:: Invalid point encountered in the attached message Object {message: Object, source: Object}
(anonymous) @ main.js [sm]:362
(anonymous) @ main.js [sm]:346
step @ /home/user123/.atom/packages/linter-phpcs/lib/main.js:5
_tickCallback @ internal/process/next_tick.js:103
linter-registry.js [sm]:137 [Linter] Error running PHPCS Error: Invalid point encountered! See console for details.
    at /home/user123/.atom/packages/linter-phpcs/lib/main.js:372:19
    at Array.map (native)
    at Object.<anonymous> (/home/user123/.atom/packages/linter-phpcs/lib/main.js:346:25)
    at Generator.next (<anonymous>)
    at step (/home/user123/.atom/packages/linter-phpcs/lib/main.js:5:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)
(anonymous) @ linter-registry.js [sm]:137
_tickCallback @ internal/process/next_tick.js:103
```

I get this this errors as a popup on every other file. Some files work fine but most of them generate this errors and I could not find out any common pattern they have.

**Comment by grappler** [comment] 2018-01-22 08:02
@nextgenthemes Does it fix it when you add `<exclude name="WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedHooknameFound"/>` within `<rule ref="WordPress-Core">`?

Related #306

**Comment by computamike** [comment] 2018-02-07 10:37
I had the same issue - I found that the linter was using a tab spacing of 1, whereas the editor was using a tab spacing of 4. Setting the tabspacing (in linter config) to 4 (matching the editor configuration) resolved the issue. A better fix might be to default the tab width setting on linter to match the editor configuration.

**Comment by nextgenthemes** [comment] 2018-09-04 20:06
I ran into this issue again now on Ubuntu 18.04 and newest Atom version. Something about this tab space setting is fucked up.

My Atom general editor setting for tabs are `hard` and `4` spaces.

I remember @computamike comment actually helped me and I got it working at some point I think. But now its simply not doing anything when I leave the tab length setting empty. The this package fails filling the console with the below:
```
main.js? [sm]:362 linter-phpcs:: Invalid point encountered in the attached message {message: {…}, source: {…}}
(anonymous) @ main.js? [sm]:362
(anonymous) @ main.js? [sm]:346
step @ /home/username/.atom/packages/linter-phpcs/lib/main.js:5
_tickCallback @ internal/process/next_tick.js:188
Promise resolved (async)
step @ /home/username/.atom/packages/linter-phpcs/lib/main.js:5
_tickCallback @ internal/process/next_tick.js:188
Promise resolved (async)
step @ /home/username/.atom/packages/linter-phpcs/lib/main.js:5
Promise resolved (async)
step @ /home/username/.atom/packages/linter-phpcs/lib/main.js:5
Promise resolved (async)
step @ /home/username/.atom/packages/linter-phpcs/lib/main.js:5
(anonymous) @ /home/username/.atom/packages/linter-phpcs/lib/main.js:5
(anonymous) @ /home/username/.atom/packages/linter-phpcs/lib/main.js:5
promises.push.Promise.then._this2.emitter.emit.number @ linter-registry.js? [sm]:101
_loop @ linter-registry.js? [sm]:99
(anonymous) @ linter-registry.js? [sm]:87
(anonymous) @ linter-registry.js? [sm]:143
step @ /home/username/.atom/packages/linter/lib/linter-registry.js:5
(anonymous) @ /home/username/.atom/packages/linter/lib/linter-registry.js:5
(anonymous) @ /home/username/.atom/packages/linter/lib/linter-registry.js:5
(anonymous) @ main.js? [sm]:125
module.exports.Emitter.simpleDispatch @ commitCommentView_item.graphql.js:112
module.exports.Emitter.emit @ commitCommentView_item.graphql.js:112
(anonymous) @ editor-linter.js? [sm]:26
later @ /home/username/.atom/packages/linter/node_modules/sb-debounce/index.js:9
setTimeout (async)
debounced @ /home/username/.atom/packages/linter/node_modules/sb-debounce/index.js:16
module.exports.Emitter.simpleDispatch @ commitCommentView_item.graphql.js:112
module.exports.Emitter.emit @ commitCommentView_item.graphql.js:112
(anonymous) @ commitCommentView_item.graphql.js:112
Promise resolved (async)
module.exports.TextBuffer.saveTo @ commitCommentView_item.graphql.js:112
module.exports.TextBuffer.save @ commitCommentView_item.graphql.js:112
save @ commitCommentView_item.graphql.js:112
promisify @ commitCommentView_item.graphql.js:112
promisify @ commitCommentView_item.graphql.js:112
saveItem @ commitCommentView_item.graphql.js:112
saveActiveItem @ commitCommentView_item.graphql.js:112
saveActivePaneItem @ commitCommentView_item.graphql.js:112
core:save @ commitCommentView_item.graphql.js:112
handleCommandEvent @ commitCommentView_item.graphql.js:112
dispatch @ commitCommentView_item.graphql.js:112
dispatchApplicationMenuCommand @ commitCommentView_item.graphql.js:112
outerCallback @ commitCommentView_item.graphql.js:112
emitThree @ events.js:136
emit @ events.js:217
linter-registry.js? [sm]:137 [Linter] Error running PHPCS Error: Invalid point encountered! See console for details.
    at main.js? [sm]:377
    at Array.map (<anonymous>)
    at Object.<anonymous> (main.js? [sm]:348)
    at Generator.next (<anonymous>)
    at step (/home/username/.atom/packages/linter-phpcs/lib/main.js:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188)
(anonymous) @ linter-registry.js? [sm]:137
_tickCallback @ internal/process/next_tick.js:188
Promise rejected (async)
_loop @ linter-registry.js? [sm]:102
(anonymous) @ linter-registry.js? [sm]:87
(anonymous) @ linter-registry.js? [sm]:143
step @ /home/username/.atom/packages/linter/lib/linter-registry.js:5
(anonymous) @ /home/username/.atom/packages/linter/lib/linter-registry.js:5
(anonymous) @ /home/username/.atom/packages/linter/lib/linter-registry.js:5
(anonymous) @ main.js? [sm]:125
module.exports.Emitter.simpleDispatch @ commitCommentView_item.graphql.js:112
module.exports.Emitter.emit @ commitCommentView_item.graphql.js:112
(anonymous) @ editor-linter.js? [sm]:26
later @ /home/username/.atom/packages/linter/node_modules/sb-debounce/index.js:9
setTimeout (async)
debounced @ /home/username/.atom/packages/linter/node_modules/sb-debounce/index.js:16
module.exports.Emitter.simpleDispatch @ commitCommentView_item.graphql.js:112
module.exports.Emitter.emit @ commitCommentView_item.graphql.js:112
(anonymous) @ commitCommentView_item.graphql.js:112
Promise resolved (async)
module.exports.TextBuffer.saveTo @ commitCommentView_item.graphql.js:112
module.exports.TextBuffer.save @ commitCommentView_item.graphql.js:112
save @ commitCommentView_item.graphql.js:112
promisify @ commitCommentView_item.graphql.js:112
promisify @ commitCommentView_item.graphql.js:112
saveItem @ commitCommentView_item.graphql.js:112
saveActiveItem @ commitCommentView_item.graphql.js:112
saveActivePaneItem @ commitCommentView_item.graphql.js:112
core:save @ commitCommentView_item.graphql.js:112
handleCommandEvent @ commitCommentView_item.graphql.js:112
dispatch @ commitCommentView_item.graphql.js:112
dispatchApplicationMenuCommand @ commitCommentView_item.graphql.js:112
outerCallback @ commitCommentView_item.graphql.js:112
emitThree @ events.js:136
emit @ events.js:217
```
When I set the tab length setting of this package to 4 package starts to run but complains that it will need spaces on all my lines because I use tabs ... but my ...

Now I am thinking my config `phpcs.xml.dist` is not loading and I am experiencing with the `disable when no config` and `search for config` setting. (Does phpcs not do this by default?) And I am actually seeing it not execute at all ... seems very bugged. Because its should run no matter if a check these settings or not. Because there is a default config. I think all this settings make the package worse. It should just run like when phpcs is run without any switches on the commandline. That works perfectly fine but this package has serious issues.

**Comment by Arcanemagus** [comment] 2018-09-28 00:44
This error message is thrown when the linter reports a position that doesn't actually exist in the document. If you are able to reliably reproduce this with a file and configuration that you are able to share I'd be happy to help you get to the root cause and get a bug reported on `phpcs`. As it stands since this isn't a bug with this package and there is nothing that I can do with the information provided I'm going to close this issue.

**Closed by Arcanemagus** 2018-09-28 00:44 UTC
