### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by nisassa** [AtomLinter/linter-phpcs#322] opened 2018-08-16 15:45 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [linter-phpcs](https://github.com/AtomLinter/linter-phpcs) package 1.6.8

### Stack Trace

Uncaught Error: spawn EACCES

```
At /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:320

Error: spawn EACCES
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:514:9)
    at BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:255:47)
    at BufferedProcess.start (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:82:18)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:69:18)
    at /packages/linter-phpcs/node_modules/atom-linter/lib/helpers.js:58:77
    at new Promise (<anonymous>)
    at /packages/linter-phpcs/node_modules/atom-linter/lib/helpers.js:23:18)
    at Generator.next (<anonymous>)
    at step (/packages/linter-phpcs/node_modules/atom-linter/lib/helpers.js:114:191)
    at /packages/linter-phpcs/node_modules/atom-linter/lib/helpers.js:114:368
    at <anonymous>
```

### Commands

```
     -0:24.4.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:18.9.0 tabs:close-all-tabs (div.title)
```

### Non-Core Packages

```
busy-signal 1.4.3 
highlight-selected 0.14.0 
intentions 1.1.5 
linter 2.2.0 
linter-phpcs 1.6.8 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
php-twig 4.0.0 
remote-ftp 2.2.0 
```

**Comment by Arcanemagus** [comment] 2018-09-28 01:01
`EACCESS` there generally means you have tried to execute a _folder_ as a program. Since you provided no steps to reproduce this I'm unable to attempt to diagnose this any further though.

I'm going to close this issue, however if you are still seeing this don't hesitate to reach out.

**Closed by Arcanemagus** 2018-09-28 01:01 UTC
